---
title: Data Science for Security Engineers
subtitle: Or, There Is No Such Thing as One-Weird-Trick
format: clean-revealjs
# format: revealjs
author:
  - name: Phil Henrickson, PhD
    affiliations: AE Business Solutions
date: last-modified
css: styles.css
editor: source
---

# Context {.large-slide}

## 

I am often asked, 

## {.large-slide}

<br>
"I don't like math, statistics, or programming.

<div style="height: 28px;"></div>
How do I be a data scientist?"

## {.large-slide background-image="images/alec-baldwin.jpg" style="color: white;"}

<br>
"I don't like math, statistics, or programming.

<div style="height: 28px;"></div>
How do I be a data scientist?"

## {.large-slide background-image="images/alec-baldwin.jpg"}

---

When someone tells me, "I want to learn about data science", I've come to realize that there are generally two different mentalities:

. . .

1) *I want to learn the **one-cool-trick** from an open source data science package that I can implement in my project with little to no effort that **will look impressive** to my higher ups who will have next to no idea what I'm talking about but will praise me for using something they can call **AI**.*

. . .

2) *Tell me where to begin on the **dark and unending path** into statistics, mathematics, and programming for the purpose of **learning from data** in order to draw uncertain inferences about data-generating processes at work in the world so that I might better **understand why things happen**.*

## {background-image="images/data-scientist-in-six-weeks.png"}

---

When someone tells me, "I want to learn about data science", I've come to realize that there are generally two different mentalities:

<div style="height: 0em;"></div>

1) *I want to learn the **one-cool-trick** from an open source data science package that I can implement in my project with little to no effort that **will look impressive** to my higher ups who will have next to no idea what I'm talking about but will praise me for using something they can call **AI**.*

. . .

2) *Tell me where to begin on the **dark and unending path** into statistics, mathematics, and programming for the purpose of **learning from data** in order to draw uncertain inferences about data-generating processes at work in the world so that I might better **understand why things happen**.*

## {background-image="images/always-be-closing.jpg"}

---

When someone tells me, "I want to learn about data science", I've come to realize that there are generally two different mentalities:

::: {.blur-text}
1) *I want to learn the **one-cool-trick** from an open source data science package that I can implement in my project with little to no effort that **will look impressive** to my higher ups who will have next to no idea what I'm talking about but will praise me for using something they can call **AI**.*
:::

<div style="height: 0em;"></div>

2) *Tell me where to begin on the **dark and unending path** into statistics, mathematics, and programming for the purpose of **learning from data** in order to draw uncertain inferences about data-generating processes at work in the world so that I might better **understand why things happen**.*

---

When someone tells me, "I want to learn about data science", I've come to realize that there are generally two different mentalities:

::: {.blur-text}
1) *I want to learn the **one-cool-trick** from an open source data science package that I can implement in my project with little to no effort that **will look impressive** to my higher ups who will have next to no idea what I'm talking about but will praise me for using something they can call **AI**.*
:::

<div style="height: 0em;"></div>

::: {.bg style="--col: #FF6F40"} 
2) *Tell me where to begin on the **dark and unending path** into statistics, mathematics, and programming for the purpose of **learning from data** in order to draw uncertain inferences about data-generating processes at work in the world so that I might better **understand why things happen**.*
:::

[This is what this talk is about.]{.fragment .fade-in}

---

To be clear, I don't believe that I can pack [semesters worth of info]{.bg style="--col: #e64173"} into twenty minutes. 

. . .

I think the best I can reasonably do is [spark some level of interest]{.bg style="--col: #FF6F40"} in what I do and why you might find it kind of interesting. Even if it will be hard.

---


I will point you towards some things I think you should check out.

. . .

I will recommend a basic technology stack.

. . .

I will list a few books to reference (and yes, some are textbooks).

. . .

But, in the end, none of that is really important.

. . .

Because first, **I want to tell you a story**.

# 1) Charles Reep and the <br> Desolation of English Football

Or, the importance of research design

## {background-image="images/charles-reep.jpg" style="color: white;"}

---

In 1950, Charles Reep was an RAF officer stationed in Yatesbury, England.

. . .

An ardent football fan, he routinely attended nearby matches. 

. . . 

While attending a football match between Swindon and Bristol Rovers on March 18, he became fed up after watching attack after attack produce no goals. He decided to record every sequence in the second half. 

. . .

Putting pen to paper, something jumped out at him: 

---

He later developed a much more elaborate system for tracking passing sequences

## {background-image="images/charles-reep-notes.jpg" style="color: white;" background-size="contain"}

## {background-image="images/royal-statistical-society.png" style="color: white;" background-size="contain"}

---

This was arguably the first-ever analytical insight into sport that led to a data-driven strategy.

. . .

England, the originator of the world's most popular sport, eventually embraced this approach. The long-ball became England's football orthodox.

. . .

And it ultimately proved to be a disaster.

. . .

Because Reep's insight was fundamentally wrong.

---

Here's the deal: 

Reep noted that `~80%` of goals came from passing sequences with **three passes or less**.

. . .

He also observed `~90%` of all passing sequences had **three passes or less**.

. . .

If goals occured completely randomly with absolutely no relationship to the length of passing sequences, how many goals would we expect to occur to find in sequences of

. . .

But he said 80%. So, given his own premise, the data indicates that passes 

---

--- 

Reep wanted to know when goals occur, so he looked at all of the sequences that resulted in goals. He found that goals typically occured among shorter passing sequences. 

. . .

. . .

But there are a lot of short passing sequences in soccer that *don't* lead to goals.

. . .

He should have been examining *all* passing sequences and asking, when do goals occur?

---

In other words, Reep solved for this:

. . .

$$
max_k \Pr(\text{Passes} = k \mid \text{Goal}) \text{ for all sequences of $k$ passes} \newline
\textnormal{ie, what is the most common number of passes when a goal has been scored?}
$$

. . .

instead of this:

$$
\Pr(\text{Goal} \mid \text{Passes} = k) \newline
\textnormal{ie, what is the probability of a goal among all sequences with $k$ passes?}
$$

If he had asked this, he might y

---


---


Why am I telling you this story?

. . .

Because I just spend two weeks in England/Scotland/Ireland, so there.

. . .

Because the single most important thing to understand about data science a mindset:

. . .

How could I prove myself wrong?

---

At 

At this point, you might very reasonably be wondering:

. . .

How does any of this apply to to my job in Network/Security?

# 2) But How Does Any of This <br> Apply to Your Job in Network/Security?

. . .

Hold on to your butts.

# 3) Okay, So What Should I Do?



